{
    'name': 'MyCodes',
    'version': '12.0.1.0',
    'summary': 'PS Cloud Homework',
    'author': "www.mypscloud.com",
    'website': 'https://www.mypscloud.com/',
    'category': 'MyOwnApps',
    'depends': ['base'],
    'data': ['security/ir.model.access.csv',
             'Views/ViewLessons.xml',
             'Views/ViewPerson.xml',
             'Views/ViewSubjects.xml',
             'Views/TrainingViews.xml'],
    'qweb': [],
    'js': [],
    'css': [],
    'auto_install': False,
    'application': True,
}